academycity/academycity/apps/core/urls.py
from django.urls import path
from .views import (home, app, update_field_model, post_ajax_create_action, activate_function, update_field_model_by_id,
                    get_data_link, get_data_json_link,
                    activate_obj_function, upload_file,
                    general_data, logmein, delete_record_from_table

                    # , get_adjective_link
                    )

app_name = "core"

urlpatterns = [
    path('', home, name='home'),
    path('app/<str:app_name>/', app, name='app'),
    path('activate_obj_function/', activate_obj_function, name='activate_obj_function'),
    path('upload_file/', upload_file, name='upload_file'),
    path('general_data/', general_data, name='general_data'),
    path('logmein/', logmein, name='logmein'),
    path('delete_record_from_table/', delete_record_from_table, name='delete_record_from_table'),

    path('post_ajax_create_action', post_ajax_create_action, name='post_ajax_create_action'),
    path('update_field_model', update_field_model, name='update_field_model'),
    path('activate_function', activate_function, name='activate_function'),
    path('update_field_model_by_id', update_field_model_by_id, name='update_field_model_by_id'),
    path('get_data_link', get_data_link, name='get_data_link'),
    path('get_data_json_link', get_data_json_link, name='get_data_json_link'),
    # path('get_adjective_link', get_adjective_link, name='get_adjective_link'),

]

academycity/academycity/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('academycity.apps.core.urls')),
    path('ml/', include('academycity.apps.acapps.ml.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

academycity/academycity/apps/core/models.py
from django.db import models
from django.db import connection
from .fields import OrderField
from .sql import TruncateTableMixin


class DataAdvancedTabsManager(models.Model):
    at_name = models.CharField(max_length=50, null=True, default="new")
    manager_content = models.JSONField(null=True)

    def __str__(self):
        return str(self.at_name)


class DataAdvancedTabs(models.Model):
    class Meta:
        verbose_name = 'DataAdvancedTabs'
        verbose_name_plural = 'DataAdvancedTabs'
        ordering = ['order']

    manager = models.ForeignKey(DataAdvancedTabsManager, on_delete=models.CASCADE, default=1)
    tab_name = models.CharField(max_length=50, null=True, default="tab")
    tab_content = models.JSONField(null=True)
    order = models.SmallIntegerField(blank=True, default=1)

    def __str__(self):
        return str(self.manager) + ":" + str(self.tab_name)


class DataAdvancedApps(models.Model):
    class Meta:
        verbose_name = 'DataAdvancedApps'
        verbose_name_plural = 'DataAdvancedApps'

    app_name = models.CharField(max_length=50, null=True, default="app_name")
    app_content = models.JSONField(null=True)

    def __str__(self):
        return str(self.app_name)


class DataAdvancedTabsCustomization(models.Model):
    tab = models.ForeignKey(DataAdvancedTabs, on_delete=models.CASCADE, default=1)
    tab_content = models.JSONField(null=True)

    def __str__(self):
        return str(self.manager) + ":" + str(self.tab_name)


class ModifyModel(object):

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {} RESTART IDENTITY CASCADE'.format(cls._meta.db_table))


class Adjectives(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return str(self.title)


class AdjectiveQuerySet(models.QuerySet):
    def adjectives(self, adjective_title):
        return self.filter(adjective__title=adjective_title)


class AdjectiveManager(models.Manager):
    def get_queryset(self):
        return AdjectiveQuerySet(self.model, self._db)

    def adjectives(self, adjective_title):
        # print(adjective_title, "\n", self.get_queryset(), "\n")
        # print(adjective_title, "\n", self.get_queryset().adjectives(adjective_title), "\n")
        return self.get_queryset().adjectives(adjective_title).order_by("order")

#
# class AdjectiveManager(models.Manager):
#     def get_queryset(self, adjective_title):
#         return super(AdjectiveManager, self).get_queryset().filter(adjective__title=adjective_title).orderby(self.order)


class AdjectivesValues(models.Model):
    adjective = models.ForeignKey(Adjectives, on_delete=models.CASCADE)
    order = models.SmallIntegerField(blank=True, default=1)
    value = models.CharField(max_length=50)

    objects = models.Manager()  # The default manager.
    adjectives = AdjectiveManager()  # Our custom manager.

    def __str__(self):
        return self.value


class Numbers(models.Model):
    SOURCES = (
        (0, 'Other'),
        (1, 'General Ledger'),
    )
    source = models.IntegerField(default=1, choices=SOURCES)
    number = models.PositiveIntegerField()

    def __str__(self):
        return str(self.source) + str(self.number)


class Debug(TruncateTableMixin, models.Model):
    value = models.CharField(max_length=1024)

    def __str__(self):
        return self.value


class GeneralData(TruncateTableMixin, models.Model):
    class Meta:
        verbose_name = 'general_data'
        verbose_name_plural = 'general_datas'
        ordering = ['app', 'group', 'data_name']
    app = models.CharField(max_length=40, default='', blank=True, null=True)
    group = models.CharField(max_length=40, default='general', blank=True, null=True)
    data_name = models.CharField(max_length=40, default='', blank=True, null=True)
    data_json = models.JSONField(null=True)

    def __str__(self):
        return str(self.data_name)

academycity/academycity/apps/core/forms.py
from django import forms
from .models import AdjectivesValues


field2 = forms.ModelChoiceField(queryset=AdjectivesValues.adjectives.get_queryset('field2'))

academycity/academycity/apps/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, authenticate, logout
from django.utils.translation import get_language, gettext_lazy as _
from django.core.management import call_command
from django.apps import apps
from django.http import JsonResponse
from django.conf import settings
import os
from django.utils.dateparse import parse_date
from django.contrib.auth.models import User
from .AdvancedTabes import AdvancedTabs
from ..core.utils import log_debug
from django.urls import reverse
from .apps_general_functions import activate_obj_function
from django.db.models.fields.related import ForeignKey, ManyToManyField, ManyToManyRel

from django.http import HttpResponse
import json
import pandas as pd
import numbers

def home(request):
    title = _('Core App')


    return render(request, 'core/home.html', {'title': title})

def app(request, app_name):
    app_ = "core"
    app_activate_function_link_ = reverse(app_+':activate_obj_function', kwargs={})
    return render(request, app_+'/advanced_tabs.html', {"atm_name": "core_"+app_name+"_tm", "app": app_,
                                               "app_activate_function_link": app_activate_function_link_,
                                               "company_obj_id": 0, "title": "Core"}
                  )

def post_ajax_create_action(request):
    try:
        obj = None
        if request.POST.get('model') and request.POST.get('model') != "":
            app_ = request.POST.get('app')
            model_ = request.POST.get('model')
            model = apps.get_model(app_label=app_, model_name=model_)
            try:
                obj_slug = request.POST.get('obj_slug')
                # print(obj_slug)
                obj = model.objects.filter(translations__language_code=get_language()).filter(translations__slug=obj_slug).all()[0]
            except Exception as er:
                pkey_ = request.POST.get('pkey')
                obj = model.objects.get(id=pkey_)

        verb_ = request.POST.get('verb')
        create_action(request.user, verb_, obj)
    except Exception as err:
        JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ok'})

def update_field_model(request):
    app_ = request.POST.get('app')
    model_ = request.POST.get('model')

    pkey_ = request.POST.get('pkey')
    value_ = request.POST.get('value')
    field_ = request.POST.get('field')
    type_ = request.POST.get('type')
    # print('1-'*20)
    # print(value_)
    # print(model_)
    # print(pkey_)
    # print('1-'*20)
    # print('2-'*20)
    # print(field_)
    # print('2-'*20)
    model = apps.get_model(app_label=app_, model_name=model_)
    try:
        obj_slug = request.POST.get('obj_slug')
        # print(obj_slug)
        obj = model.objects.filter(translations__language_code=get_language()).filter(translations__slug=obj_slug).all()[0]
    except Exception as er:
        obj = model.objects.get(id=pkey_)
    # print(obj)
    # print('3-'*20)
    # print(type_)
    # print('4-'*20)
    if type_ == "checkbox":
        if value_ == 'true':
            value_ = True
        else:
            value_ = False
    elif type_ == "date":
        value_ = parse_date(value_)
    elif type_ == "multiple_select":
        value_ = value_.split(",")
        for k in obj.instructors.all():
            obj.instructors.remove(k)
        for i in value_:
            u_ins = User.objects.get(id=int(i))
            obj.instructors.add(u_ins)
        return JsonResponse({'status': 'ok'})
    try:
        # print(value_)
        s = 'obj.' + field_ + ' = value_'
        # print(s)
        # print('-'*30)
        # print(s)
        # print('-'*30)
        exec(s)
        obj.save()
        if model_ == "Game" and field_ == "number_of_periods":
            obj.get_schedule_period_dates
        return JsonResponse({'status': 'ok'})
    except Exception as e:
        # print('-'*30)
        # print("err")
        # print(e)
        # print("err")
        # print('-'*30)
        pass
        return JsonResponse({'status': 'ko'})

def create_db_backup():
    call_command('dbbackup', compress=True, clean=True)

def clean_registrations(request):
    clean_accounting_registrations()

def activate_function(request):
    # var dic_ = {"obj": "AdvancedTabs", "atm": atm_.my_name, "app": atm_.my_app, "fun": "add_tab",
    #             "params": {"tab_name": tab_name_}}
    try:
        dic_ = request.POST["dic"]
        dic_ = eval(dic_)
        # print("-"*50, "\n", "core: 9111-1: dic\n", dic_, "\n", "-"*50, "\n")
        #
        obj_ = dic_["obj"]
        atm_ = dic_["atm"]
        app_ = dic_["app"]
        fun_ = dic_["fun"]
        params_ = dic_["params"]
        # print("core\n9005: params_\n", "-"*50, params_, '\n', "-"*50)
        s = obj_ + "('"+atm_+"', '"+app_+"')." + fun_ + "(params_)"

        # print("core\n", "9010: s=\n", s, "\n", "-"*50)

        result = eval(s)
        # print('-3'*20)
        dic = {'status': 'ok', 'result': result}
        # print("core\n", "9015: dic=\n", dic, "\n", "-"*50)
    except Exception as ex:
        print("90265-55 Error core activate_function: "+str(ex))
        dic = {'status': 'ko', 'result': "{}"}
    return JsonResponse(dic)

def update_field_model_by_id(request, foreign=None):
    log_debug("update_field_model_by_id 0")
    dic_ = request.POST["dic"]
    # print('90155-100 core update_field_model_by_id: dic_\n', '-'*50,"\n", dic_, "\n", '-'*50)
    # log_debug(dic_) # size is 1024 chars
    dic_ = eval(dic_)
    # print('90155-100-1 core update_field_model_by_id: dic_\n', '-'*50,"\n", dic_, "\n", '-'*50)
    element_id_ = ""
    try:
        element_id_ = dic_["element_id"]
    except Exception as ex:
        pass

    try:
        app_ = dic_['app']
        # print(dic_['model'])
        model_ = dic_['model']
        pkey_ = dic_['pkey']
        fields_ = dic_['fields']
        type_ = dic_['type']
        company_obj_id_ = dic_['company_obj_id']
        parent_model_ = dic_['parent_model']
        parent_model = apps.get_model(app_label=app_, model_name=app_+"web")
        company_obj = parent_model.objects.get(id=company_obj_id_)
    except Exception as ex:
        log_debug("Error 2000:" + str(ex))

    try:
        model = apps.get_model(app_label=app_, model_name=model_)
    except Exception as ex:
        log_debug("Error 2001:" + str(ex))
        return JsonResponse({'status': 'ko'})
    p_key_field_name = ""

    # print("9087-67 pkey_", pkey_)

    if pkey_ == "new":
        s = ""
        if model.model_field_exists(app_+'_web') and isinstance(model._meta.get_field(app_+'_web'), ForeignKey):
            # print("it is a foreign key")
            s = "model.objects.create("
            s += app_ + '_web=company_obj '
        # print("9066-66:\n" + s)
        # print(parent_model_)
        if parent_model_ != "":
            # print('9040\n', s)
            parent_pkey_ = dic_['parent_pkey']
            parent_model__ = apps.get_model(app_label=app_, model_name=parent_model_)
            parent_model_fk_name = parent_model_[:-1]
            parent_obj__ = parent_model__.objects.get(id=parent_pkey_)
            if s == "":
                s = "model.objects.create("
            else:
                s += ", "
            s += parent_model_fk_name + '=parent_obj__'
        try:
            # print('9045-0')
            space_ = ", "
            if s == "":
                s = "model.objects.create("
                space_ = ""
            # print("9045-1 ", s)

            foreign_keys = dic_["foreign_keys"]
            # print("9046 ", foreign_keys, "9046 ")

            for k in foreign_keys:
                t_model = apps.get_model(app_label=app_, model_name=foreign_keys[k]["foreign_table"])
                p_key_field_name = t_model._meta.pk.name
                try:
                    # print(k, foreign_keys[k]["value"])
                    n_p_key = int(foreign_keys[k]["value"])
                    # print('t_model.objects.get('+p_key_field_name+'=n_p_key)')
                    obj__ = eval('t_model.objects.get('+p_key_field_name+'=n_p_key)')
                    # print("=6"*10)
                    # print(obj__)
                    # print("=6"*10)
                except Exception as ex:
                    print("err 800-1: "+str(ex))
                try:
                    myVars = vars()
                except Exception as ex:
                    print("err 800: "+str(ex))
                try:
                    myVars[k] = obj__
                except Exception as ex:
                    print("err 900: "+str(ex))
                    log_debug("err 900: "+str(ex))
                s += space_+k+'='+k
                space_ = ", "
        except Exception as ex:
            pass
            # print("7010-1 save with fkey error " + str(ex))
        s += ')'

        # print("9066-661:\n" + s)

        try:
            # print("9055-89\n" + s, "\n", "-"*30)
            # print(model)
            obj = eval(s)
        except Exception as ex:
            print("error701-701-1 "+str(ex))
        try:
            p_key_field_name = model._meta.pk.name
            if model.model_field_exists(app_ + '_web') and isinstance(model._meta.get_field(app_ + '_web'), ManyToManyField):
                s = "obj."+app_ + '_web.add(company_obj)'
                # print("9035\n", s)
                eval(s)
                # print("9052")
                obj.save()
                print("9055")
            # print("9055-89\n", "-"*30)
        except Exception as ex:
            print("error701-701 "+str(ex))
            log_debug("error701 "+str(ex))
    else:
        try:
            obj_slug = request.POST.get('obj_slug')
            # print(obj_slug)
            obj = \
            model.objects.filter(translations__language_code=get_language()).filter(translations__slug=obj_slug).all()[0]
        except Exception as er:

academycity/academycity/apps/core/templates/core/advanced_tabs.html
{% load static i18n %}
{% load core_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{title}}</title>
    <link rel='stylesheet' id='ac-advanced-tabs'  href="{% static 'css/academycity/core/ac_advanced_tabs_v8.css' %}" media='all' />
<!--  RichText  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet" />
    <link rel='stylesheet' id='rich_text'  href="{% static 'css/academycity/other/rich_text.css' %}" media='all' />
<!--  End RichText  -->

{% block add_style %}

{% endblock add_style %}

{% block add_script_head %}

{% endblock add_script_head %}


</head>
<body id="body_">

{% block add_script %}

{% endblock add_script %}

<script src="{% static 'js/academycity/core/AT_v202.js' %}"></script>

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/npm/cookie/js.cookie.min.js' %}"></script>
<script src="//cdn.rawgit.com/rainabba/jquery-table2excel/1.1.0/dist/jquery.table2excel.min.js"></script>

<script src="{% static 'vendor/fontawesome-free-5.11.2-web/a076d05399.js' %}"></script>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/luxon@1.26.0"></script>

{% if app == "training" %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
{% else %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.1/dist/chart.js"></script>
{% endif %}

<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.1/dist/chart.js"></script>-->

<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-luxon@1.0.0"></script>

<script src="{% static 'js/chartjs/chartjs-chart-financial.js'  %}" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="{% static 'js/chartjs/style.css' %}">
<link rel="icon" href="{% static 'images/favicon.ico'  %}"/>

<script>
var csrftoken = Cookies.get('csrftoken');
function csrfSafeMethod(method) {
// these HTTP methods do not require CSRF protection
return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
beforeSend: function(xhr, settings) {
  if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
    xhr.setRequestHeader("X-CSRFToken", csrftoken);
  }
}
});
var dic={
"my_name":"{{atm_name}}",
"my_app":"{{app}}",
"logmein_link":'{{logmein_link}}',
"delete_record_from_table_link":'{% url "core:delete_record_from_table" %}',
"activate_function_link":'{% url "core:activate_function" %}',
"company_obj_id":{{company_obj_id}},
"body_":document.getElementById("body_"),
"update_field_link":'{% url "core:update_field_model_by_id" %}',
"activate_obj_function_link":'{{app_activate_function_link}}',
"upload_file_link":'{% url "core:upload_file" %}',
"get_data_link":'{% url "core:get_data_link" %}',
"general_data":'{% url "core:general_data" %}',
"get_data_json_link":'{% url "core:get_data_json_link" %}',
"is_show_btns":{%if request.user|has_group:"admins"%}true{% else %}false{%endif%},
"default_battalion":"{{ default_battalion }}",
"default_entity":"{{ default_entity }}",
"entity_name":"{{ entity_name }}",
"user_id":"{{ user_id }}"
}

$(document).ready(function(){
 var {{atm_name}}=new AdvancedTabsManager();
 //atm = {{atm_name}}
 atm = {{atm_name}}.create_atm(dic)
{% block domready %}
{% endblock %}
});
</script>
</body>
</html>

academycity/academycity/apps/core/templates/core/any_chart.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>JavaScript Stock Chart</title>
    <script src="https://cdn.anychart.com/releases/8.11.0/js/anychart-core.min.js"></script>
    <script src="https://cdn.anychart.com/releases/8.11.0/js/anychart-stock.min.js"></script>
    <script src="https://cdn.anychart.com/releases/8.11.0/js/anychart-data-adapter.min.js"></script>

    <script src="https://cdn.anychart.com/releases/8.11.0/js/anychart-ui.min.js"></script>
    <script src="https://cdn.anychart.com/releases/8.11.0/js/anychart-exports.min.js"></script>

    <link href="https://cdn.anychart.com/releases/8.11.0/css/anychart-ui.min.css" type="text/css" rel="stylesheet">
    <link href="https://cdn.anychart.com/releases/8.11.0/fonts/css/anychart-font.min.css" type="text/css" rel="stylesheet">

    <title>{{ticker}}</title>

    <style type="text/css">
      html, body, #container {
        width: 100%; height: 100%; margin: 0; padding: 0;
      }
    </style>
  </head>
<body id="body_">

<script>
alert(1)

      anychart.onDocumentReady(
      function () {
      anychart.data.loadCsvFile(
        'http://query1.finance.yahoo.com/v7/finance/download/TSLA?period1=1&period2=3045692203&interval=1d&events=history&includeAdjustedClose=true',
        function (data) {
          // create data table on loaded data
          var dataTable = anychart.data.table();
          dataTable.addData(data);

          // map loaded data for the candlestick series
          var mapping = dataTable.mapAs({
            open: 1,
            high: 2,
            low: 3,
            close: 4
          });
        }
      );
    })
    ;

    var chart = anychart.stock();

    // create first plot on the chart
    var plot = chart.plot(0);

    // set grid settings
    plot.yGrid(true).xGrid(true).yMinorGrid(true).xMinorGrid(true);


    var series = plot.candlestick(mapping).name('Tesla');
    series.legendItem().iconType('rising-falling');
    // create scroller series with mapped data
    chart.scroller().candlestick(mapping);


    // set chart selected date/time range
    chart.selectRange('2020-11-27', '2021-11-26');
    // create range picker
    var rangePicker = anychart.ui.rangePicker();
    // init range picker
    rangePicker.render(chart);
    // create range selector
    var rangeSelector = anychart.ui.rangeSelector();
    // init range selector
    rangeSelector.render(chart)
    // sets the title of the chart


    chart.title('Tesla Inc. Stock Chart');
    // set container id for the chart
    chart.container('container');
    // initiate chart drawing
    chart.draw();
</script>
</body>
</html>

academycity/academycity/apps/core/templates/core/home.html
{% extends "academycity/base.html" %}

{% block content %}


<div class="container">
core<br/>
core<br/>
core<br/>
core<br/>
core<br/>
core<br/>
core<br/>


</div>
{% endblock %}